touch: fts: fix build error due to -isystem removal
Upstream commit 04e85bbf71c9 ("isystem: delete global -isystem compile
option") requires using in-tree minimal stddef header. Fixes:

  touch/fts/ftm5/fts_lib/ftsTime.c:30:10:
  fatal error: 'stdarg.h' file not found
  #include <stdarg.h>
           ^~~~~~~~~~

Bug: 215712060
Signed-off-by: Carlos Llamas <cmllamas@google.com>
Change-Id: I02058cb584d87823a455f06aaae589470ef099c1